#!/bin/bash


# Go to the case directory
cd pitzDaily

# Run the checkMesh utility
checkMesh

#Run the simulation and capture logs
simpleFoam > log

# Run the post-processing utility (e.g., paraFoam)
paraFoam


echo "Allrun.sh script execution completed."

